
env: flex
runtime: nodejs10

service: app-planning-poker-react


manual_scaling:
  instances: 1

network:
  session_affinity: true

handlers:

  - url: /(.*\.(json|ico|js))$
    static_files: build/\1
    upload: build/.*\.(json|ico|js)$

  - url: .*
    static_files: build/index.html
    upload: build/index.html